
export const MASTER_CHEMICAL_NAMES = [
  "1,2-Dichloroethane", "1,4-Dioxane", "1-Butanol", "1-Chloronaphthalene", "1-Pentanol", "1-Propanol",
  "2,2,4-Trimethylpentane", "2,4-Dinitrofluorobenzene", "2-Hydroxybenzaldehyde", "2-Iodopropane",
  "2-Pentanone", "2-Propanol", "4-Methoxybenzaldehyde", "4-Methyl-2-pentanol", "Acetaldehyde",
  "Acetic acid", "Acetic anhydride", "Acetone", "Acetonitrile", "Ammonia solution 25%", "Ammonia solution 35%",
  "Benzaldehyde", "Benzene", "Boron trifluoride - methanol", "Buffer solution pH 10", "Buffer solution pH 4",
  "Buffer solution pH 7", "Chloroform", "Cyclohexane", "Dichloromethane", "Diethyl ether", "Diethylamine",
  "Dimethylsulfoxide", "Di-n-butylamine phosphate", "Ethanol 96%", "Ethanol absolute", "Ethyl acetate",
  "Ethyl formate", "Ethylene glycol", "Ethylene glycol monomethyl", "Formaldehyde solution 37%", "Formamide",
  "Formic acid", "Glycerol", "Hexachloroplatinic (IV) acid", "Hydriodic acid 57%", "Hydrochloric acid 37%",
  "Hydrofluoric acid 48%", "Hydrogen peroxide 30%", "Iodine monochloride", "Iodomethane", "Isoamyl alcohol",
  "Isobutanol", "Isopropyl acetate", "Liquinox", "Methanol", "Methyl benzoate", "Methyl isobutyl ketone",
  "Morpholine", "N,N-Dimethylacetamide", "N,N-Dimethylaniline", "N,N-Dimethylformamide", "n-Butyl acetate",
  "n-Heptane", "n-Hexane", "Nitrate standard solution", "Nitric acid 65%", "n-Octane", "n-Pentane",
  "Ortho-Phosphoric acid 85%", "O-Xylene", "Paraffin Liquid", "Perchloric acid 70 - 72%", "Petroleum ether",
  "Polyethylene glycol 200", "Potassium chloride solution", "Potassium standard solution", "Pyridine",
  "Pyruvic acid", "Propylene glycol", "RBS A 156", "RBS A 375", "Sodium standard solution", "Solvent",
  "Soybean oil", "Squalane", "Sulfuric acid 95 - 97%", "Tert-Butanol", "Tetrahydrofuran", "Tetramethylammonium",
  "Thioglycolic acid", "Titanium (III) chloride 20%", "Titrant 5", "Toluene", "Triethylamine",
  "Trifluoroacetic acid", "Triton X - 100", "Tween 80", "Zinc standard solution", "1-Butanesulfonic acid",
  "1-Cetylpyridinium chloride", "1-Heptanesulfonic acid", "1-Hexanesulfonic acid", "1-Naphthol",
  "1-Naphthylammonium chloride", "1-Octanesulfonic acid", "1-Pentanesulfonic acid", "2,4-Dinitrophenylhydrazine",
  "2,6-Di-tert-butyl-4-methylphenol", "2,7-Naphthalenediol", "2-Naphthol", "3,5-Dinitrobenzoyl chloride",
  "4-Aminobenzoic acid", "5-Methoxy-2-mercaptobenzimidazole", "Acetoacetamide", "Adipic acid",
  "Aldehyde dehydrogenase", "Alizarin-3-methylamine", "Ammonium acetate", "Ammonium carbonate",
  "Ammonium chloride", "Ammonium dihydrogen phosphate", "Ammonium formate", "Ammonium heptamolybdate",
  "Ammonium iron(III) sulfate", "Ammonium nitrate", "Ammonium peroxodisulfate", "Ammonium sulfate",
  "Ammonium thiocyanate", "Anthron", "Antimony(III) chloride", "Barium chloride dihydrate",
  "Barium hydroxide octahydrate", "Benzethonium chloride", "Benzoic acid", "Beta-Nicotinamide adenine",
  "Bismuth(III) subnitrate", "Boric acid", "Bromocresol green", "Bromocresol purple", "Bromophenol blue",
  "Bromothymol blue", "Calcium acetate", "Calcium carbonate", "Calcium chloride anhydrous", "Calcium hydroxide",
  "Calcium sulfate dihydrate", "Calconcarboxylic acid", "Catechol (Pyrocatechol)", "Cerium(IV) sulfate",
  "Cetyltrimethylammonium bromide", "Chloramin B", "Chloramine T trihydrate", "Chloroacetic acid",
  "Chromotropic acid disodium", "Citric acid monohydrate", "Cobalt(II) chloride", "Cobalt(II) nitrate",
  "Copper(II) sulfate pentahydrate", "Di-ammonium hydrogen phosphate", "Di-ammonium oxalate", "Diphenylamine",
  "Di-potassium hydrogen phosphate", "Di-sodium hydrogen phosphate", "Di-sodium tartrate dihydrate",
  "Di-sodium tetraborate decahydrate", "Dithizone", "EDTA disodium salt", "Eriochrome Black T", "Fuchsin",
  "Glycine", "Glycolic acid", "Hexamine", "Hydrazinium sulfate", "Hydroxylammonium chloride",
  "Hydroxynaphthol blue", "Iodine", "Iodine monobromide", "Iron(II) ethylenediammonium", "Iron(II) sulfate",
  "Iron(III) chloride hexahydrate", "Iron(III) sulfate hydrate", "Lanthanum(III) oxide", "Lead(II) acetate",
  "Lead(II) nitrate", "L-Isoleucine", "L-Leucine", "Magnesium", "Magnesium oxide", "Magnesium sulfate",
  "Manganese(II) sulfate", "Manganese(IV) oxide", "Mercury(II) acetate", "Mercury(II) chloride",
  "Methyl orange", "Methyl red", "Molybdic acid", "N-(1-Naphthyl)ethylenediamine", "Naphthalene",
  "Ninhydrin", "Oleanolic acid", "Oxalic acid dihydrate", "p-Benzoquinone", "Phenol", "Phenol red",
  "Phenolphthalein", "Phenyldrazine hydrochloride", "Phosphomolybdic acid", "Phosphorous acid",
  "Phthalic anhydride", "Potassium acetate", "Potassium bromate", "Potassium bromide", "Potassium carbonate",
  "Potassium chloride", "Potassium dichromate", "Potassium dihydrogen phosphate", "Potassium hexacyanoferrate",
  "Potassium hydroxide", "Potassium iodate", "Potassium iodide", "Potassium nitrate", "Potassium permanganate",
  "Potassium sodium tartrate", "Potassium sulfate", "Potassium thiocyanate", "Resorcinol", "Salicylaldazine",
  "Silver nitrate", "Sodium acetate anhydrous", "Sodium arsenate dibasic", "Sodium carbonate", "Sodium chloride",
  "Sodium dihydrogen phosphate", "Sodium docosate", "Sodium dodecyl sulfate", "Sodium fluoride",
  "Sodium hexanitrocobaltate", "Sodium hydrogen carbonate", "Sodium hydrogen tartrate", "Sodium hydroxide",
  "Sodium metabisulfite", "Sodium nitrite", "Sodium nitroprusside", "Sodium perchlorate", "Sodium periodate",
  "Sodium pyrophosphate", "Sodium salicylate", "Sodium sulfate anhydrous", "Sodium sulfide nanohydrate",
  "Sodium sulfite anhydrous", "Sodium thiosulfate", "Starch", "Sulfanilic acid", "Tartaric acid",
  "Tetra-n-butylammonium bromide", "Tetra-n-butylammonium hydrogen", "Tetra-n-butylammonium hydroxide",
  "Than hoạt tính", "Thioacetamide", "Thymol", "Trichloroacetic acid", "Tris(hydroxymethyl)aminomethane",
  "Tri-sodium citrate", "Tri-sodium phosphate", "Vanilline", "Xylenol orange", "Zinc", "Zinc acetate",
  "Zinc chloride", "Zinc sulfate heptahydrate"
];
